// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// SQL queries for the user feature. Each block becomes a method on the
	// generated internal/user/db.Querier interface. Names come from the
	// @name annotation on the first line of each block.
	// PLACEHOLDER — replaced in step 2 with the real queries extracted
	// from internal/user/repository.go.
	PlaceholderUserQuery(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
