// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package db

import (
	"context"
)

const placeholderMovieQuery = `-- name: PlaceholderMovieQuery :one

SELECT 1
`

// SQL queries for the movie feature. Each block becomes a method on the
// generated internal/movie/db.Querier interface. Names come from the
// @name annotation on the first line of each block.
// PLACEHOLDER — replaced in step 2 with the real queries extracted
// from internal/movie/repository.go.
func (q *Queries) PlaceholderMovieQuery(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholderMovieQuery)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
