// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeeds = `-- name: CountFeeds :one
SELECT COUNT(*)
FROM feeds
WHERE (
        $1::text IS NULL
        OR title       ILIKE $1
        OR description ILIKE $1
      )
  AND deleted_at IS NULL
`

func (q *Queries) CountFeeds(ctx context.Context, query pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countFeeds, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertFeed = `-- name: InsertFeed :one
INSERT INTO feeds (title, description, rating)
VALUES ($1, $2, $3)
RETURNING id, title, description, rating, created_at, updated_at, deleted_at
`

type InsertFeedParams struct {
	Title       string
	Description pgtype.Text
	Rating      pgtype.Float8
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, insertFeed, arg.Title, arg.Description, arg.Rating)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const queryFeedsPage = `-- name: QueryFeedsPage :many

SELECT id, title, description, rating, created_at, updated_at, deleted_at
FROM feeds
WHERE (
        $1::text IS NULL
        OR title       ILIKE $1
        OR description ILIKE $1
      )
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT  $3::int
OFFSET $2::int
`

type QueryFeedsPageParams struct {
	Query    pgtype.Text
	Offset   int32
	PageSize int32
}

// SQL queries for the feed feature. Each block becomes a method on the
// generated internal/feed/db.Querier interface. The first line of each
// block is the @name annotation (which becomes the method name) and the
// query type (`:one`, `:many`, `:exec`, `:execrows`).
//
// `sqlc.narg('query')` returns NULL when the caller does not set the
// `query` parameter, which short-circuits the LIKE clauses via the
// `IS NULL OR ...` pattern. When the caller sets it, the caller is
// responsible for wrapping the search term in `%` wildcards.
func (q *Queries) QueryFeedsPage(ctx context.Context, arg QueryFeedsPageParams) ([]Feed, error) {
	rows, err := q.db.Query(ctx, queryFeedsPage, arg.Query, arg.Offset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFeed = `-- name: SoftDeleteFeed :execrows
UPDATE feeds
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFeed(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFeed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET title       = $1,
    description = $2,
    rating      = $3,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, title, description, rating, created_at, updated_at, deleted_at
`

type UpdateFeedParams struct {
	Title       string
	Description pgtype.Text
	Rating      pgtype.Float8
	ID          int32
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, updateFeed,
		arg.Title,
		arg.Description,
		arg.Rating,
		arg.ID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
