// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFeeds = `-- name: CountFeeds :one
SELECT COUNT(*)
FROM feeds
WHERE (
        $1::text IS NULL
        OR title       ILIKE $1
        OR description ILIKE $1
      )
  AND deleted_at IS NULL
  AND user_id   = $2
`

type CountFeedsParams struct {
	Query  pgtype.Text
	UserID int64
}

func (q *Queries) CountFeeds(ctx context.Context, arg CountFeedsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFeeds, arg.Query, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFeedByIDForUser = `-- name: GetFeedByIDForUser :one
SELECT id, user_id, title, description, created_at, updated_at, deleted_at
FROM feeds
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetFeedByIDForUserParams struct {
	ID     int32
	UserID int64
}

type GetFeedByIDForUserRow struct {
	ID          int32
	UserID      int64
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

// Single-row read for GET /api/feeds/{id}. The same WHERE filters on
// id + user_id + deleted_at IS NULL that GetAll uses, so a missing id
// AND a cross-owner id both resolve to pgx.ErrNoRows at the sqlc
// layer — the repo translates that to feed.ErrNotFound (single
// sentinel, no existence leak).
func (q *Queries) GetFeedByIDForUser(ctx context.Context, arg GetFeedByIDForUserParams) (GetFeedByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getFeedByIDForUser, arg.ID, arg.UserID)
	var i GetFeedByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertFeed = `-- name: InsertFeed :one
INSERT INTO feeds (user_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, title, description, created_at, updated_at, deleted_at, user_id
`

type InsertFeedParams struct {
	UserID      int64
	Title       string
	Description pgtype.Text
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, insertFeed, arg.UserID, arg.Title, arg.Description)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
	)
	return i, err
}

const queryFeedsPage = `-- name: QueryFeedsPage :many

SELECT id, user_id, title, description, created_at, updated_at, deleted_at
FROM feeds
WHERE (
        $1::text IS NULL
        OR title       ILIKE $1
        OR description ILIKE $1
      )
  AND deleted_at IS NULL
  AND user_id   = $2
ORDER BY created_at DESC, id DESC
LIMIT  $4::int
OFFSET $3::int
`

type QueryFeedsPageParams struct {
	Query    pgtype.Text
	UserID   int64
	Offset   int32
	PageSize int32
}

type QueryFeedsPageRow struct {
	ID          int32
	UserID      int64
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

// SQL queries for the feed feature. Each block becomes a method on the
// generated internal/feed/db.Querier interface. The first line of each
// block is the @name annotation (which becomes the method name) and the
// query type (`:one`, `:many`, `:exec`, `:execrows`).
//
// `sqlc.narg('query')` returns NULL when the caller does not set the
// `query` parameter, which short-circuits the LIKE clauses via the
// `IS NULL OR ...` pattern. When the caller sets it, the caller is
// responsible for wrapping the search term in `%` wildcards.
//
// Every query filters on user_id — feeds are owner-scoped. The handler
// always supplies a user_id (the JWT subject); we use plain
// `= @user_id` rather than `sqlc.narg` so a NULL filter can't accidentally
// leak rows from every user.
func (q *Queries) QueryFeedsPage(ctx context.Context, arg QueryFeedsPageParams) ([]QueryFeedsPageRow, error) {
	rows, err := q.db.Query(ctx, queryFeedsPage,
		arg.Query,
		arg.UserID,
		arg.Offset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryFeedsPageRow{}
	for rows.Next() {
		var i QueryFeedsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryFeedsPageAsc = `-- name: QueryFeedsPageAsc :many
SELECT id, user_id, title, description, created_at, updated_at, deleted_at
FROM feeds
WHERE (
        $1::text IS NULL
        OR title       ILIKE $1
        OR description ILIKE $1
      )
  AND deleted_at IS NULL
  AND user_id   = $2
ORDER BY created_at ASC, id ASC
LIMIT  $4::int
OFFSET $3::int
`

type QueryFeedsPageAscParams struct {
	Query    pgtype.Text
	UserID   int64
	Offset   int32
	PageSize int32
}

type QueryFeedsPageAscRow struct {
	ID          int32
	UserID      int64
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

// Ascending counterpart of QueryFeedsPage. Two separate queries keep
// the ORDER BY literal (sqlc doesn't interpolate direction tokens),
// and let the planner pick a different index if one ever lands for
// ASC. The id tiebreaker flips to ASC so pagination stays consistent
// within a sort direction.
func (q *Queries) QueryFeedsPageAsc(ctx context.Context, arg QueryFeedsPageAscParams) ([]QueryFeedsPageAscRow, error) {
	rows, err := q.db.Query(ctx, queryFeedsPageAsc,
		arg.Query,
		arg.UserID,
		arg.Offset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryFeedsPageAscRow{}
	for rows.Next() {
		var i QueryFeedsPageAscRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFeed = `-- name: SoftDeleteFeed :execrows
UPDATE feeds
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteFeedParams struct {
	ID     int32
	UserID int64
}

func (q *Queries) SoftDeleteFeed(ctx context.Context, arg SoftDeleteFeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFeed, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET title       = $1,
    description = $2,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $3 AND user_id = $4 AND deleted_at IS NULL
RETURNING id, title, description, created_at, updated_at, deleted_at, user_id
`

type UpdateFeedParams struct {
	Title       string
	Description pgtype.Text
	ID          int32
	UserID      int64
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, updateFeed,
		arg.Title,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
	)
	return i, err
}
