// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountFeeds(ctx context.Context, query pgtype.Text) (int64, error)
	InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error)
	// SQL queries for the feed feature. Each block becomes a method on the
	// generated internal/feed/db.Querier interface. The first line of each
	// block is the @name annotation (which becomes the method name) and the
	// query type (`:one`, `:many`, `:exec`, `:execrows`).
	//
	// `sqlc.narg('query')` returns NULL when the caller does not set the
	// `query` parameter, which short-circuits the LIKE clauses via the
	// `IS NULL OR ...` pattern. When the caller sets it, the caller is
	// responsible for wrapping the search term in `%` wildcards.
	QueryFeedsPage(ctx context.Context, arg QueryFeedsPageParams) ([]Feed, error)
	// Ascending counterpart of QueryFeedsPage. Two separate queries keep
	// the ORDER BY literal (sqlc doesn't interpolate direction tokens),
	// and let the planner pick a different index if one ever lands for
	// ASC. The id tiebreaker flips to ASC so pagination stays consistent
	// within a sort direction.
	QueryFeedsPageAsc(ctx context.Context, arg QueryFeedsPageAscParams) ([]Feed, error)
	SoftDeleteFeed(ctx context.Context, id int32) (int64, error)
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
