// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountFeeds(ctx context.Context, arg CountFeedsParams) (int64, error)
	// Single-row read for GET /api/feeds/{id}. The same WHERE filters on
	// id + user_id + deleted_at IS NULL that GetAll uses, so a missing id
	// AND a cross-owner id both resolve to pgx.ErrNoRows at the sqlc
	// layer — the repo translates that to feed.ErrNotFound (single
	// sentinel, no existence leak).
	GetFeedByIDForUser(ctx context.Context, arg GetFeedByIDForUserParams) (GetFeedByIDForUserRow, error)
	InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error)
	// SQL queries for the feed feature. Each block becomes a method on the
	// generated internal/feed/db.Querier interface. The first line of each
	// block is the @name annotation (which becomes the method name) and the
	// query type (`:one`, `:many`, `:exec`, `:execrows`).
	//
	// `sqlc.narg('query')` returns NULL when the caller does not set the
	// `query` parameter, which short-circuits the LIKE clauses via the
	// `IS NULL OR ...` pattern. When the caller sets it, the caller is
	// responsible for wrapping the search term in `%` wildcards.
	//
	// Every query filters on user_id — feeds are owner-scoped. The handler
	// always supplies a user_id (the JWT subject); we use plain
	// `= @user_id` rather than `sqlc.narg` so a NULL filter can't accidentally
	// leak rows from every user.
	QueryFeedsPage(ctx context.Context, arg QueryFeedsPageParams) ([]QueryFeedsPageRow, error)
	// Ascending counterpart of QueryFeedsPage. Two separate queries keep
	// the ORDER BY literal (sqlc doesn't interpolate direction tokens),
	// and let the planner pick a different index if one ever lands for
	// ASC. The id tiebreaker flips to ASC so pagination stays consistent
	// within a sort direction.
	QueryFeedsPageAsc(ctx context.Context, arg QueryFeedsPageAscParams) ([]QueryFeedsPageAscRow, error)
	SoftDeleteFeed(ctx context.Context, arg SoftDeleteFeedParams) (int64, error)
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
