// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Feed struct {
	ID          int32
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	UserID      int64
}

type FeedEmbedding struct {
	FeedID      int32
	UserID      int64
	Embedding   pgvector.Vector
	ChunkText   string
	ContentHash []byte
	EmbeddedAt  pgtype.Timestamptz
}
