// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	DeleteFeedEmbedding(ctx context.Context, feedID int32) error
	// SQL queries for the RAG-over-feeds feature. Each block becomes a
	// method on the generated internal/rag/db.Querier interface.
	//
	// All queries scope by user_id — retrieval cannot return another
	// user's feed embeddings even if a bug desyncs the denormalised
	// user_id (the retriever JOINs back to feeds and applies the
	// user_id filter on both sides as defence-in-depth).
	GetFeedEmbeddingHash(ctx context.Context, feedID int32) ([]byte, error)
	ListFeedsWithoutEmbeddings(ctx context.Context, arg ListFeedsWithoutEmbeddingsParams) ([]ListFeedsWithoutEmbeddingsRow, error)
	RetrieveFeedPassages(ctx context.Context, arg RetrieveFeedPassagesParams) ([]RetrieveFeedPassagesRow, error)
	UpsertFeedEmbedding(ctx context.Context, arg UpsertFeedEmbeddingParams) error
}

var _ Querier = (*Queries)(nil)
