// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rag.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const deleteFeedEmbedding = `-- name: DeleteFeedEmbedding :exec
DELETE FROM feed_embeddings WHERE feed_id = $1
`

func (q *Queries) DeleteFeedEmbedding(ctx context.Context, feedID int32) error {
	_, err := q.db.Exec(ctx, deleteFeedEmbedding, feedID)
	return err
}

const getFeedEmbeddingHash = `-- name: GetFeedEmbeddingHash :one

SELECT content_hash FROM feed_embeddings WHERE feed_id = $1
`

// SQL queries for the RAG-over-feeds feature. Each block becomes a
// method on the generated internal/rag/db.Querier interface.
//
// All queries scope by user_id — retrieval cannot return another
// user's feed embeddings even if a bug desyncs the denormalised
// user_id (the retriever JOINs back to feeds and applies the
// user_id filter on both sides as defence-in-depth).
func (q *Queries) GetFeedEmbeddingHash(ctx context.Context, feedID int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFeedEmbeddingHash, feedID)
	var content_hash []byte
	err := row.Scan(&content_hash)
	return content_hash, err
}

const listFeedsWithoutEmbeddings = `-- name: ListFeedsWithoutEmbeddings :many
SELECT id, user_id, title, description, created_at, updated_at, deleted_at
FROM feeds f
WHERE f.user_id = $1
  AND f.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM feed_embeddings fe WHERE fe.feed_id = f.id
  )
ORDER BY f.created_at ASC
LIMIT $2
`

type ListFeedsWithoutEmbeddingsParams struct {
	UserID int64
	Limit  int32
}

type ListFeedsWithoutEmbeddingsRow struct {
	ID          int32
	UserID      int64
	Title       string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) ListFeedsWithoutEmbeddings(ctx context.Context, arg ListFeedsWithoutEmbeddingsParams) ([]ListFeedsWithoutEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, listFeedsWithoutEmbeddings, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedsWithoutEmbeddingsRow{}
	for rows.Next() {
		var i ListFeedsWithoutEmbeddingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retrieveFeedPassages = `-- name: RetrieveFeedPassages :many
SELECT
    fe.feed_id,
    f.title,
    f.description,
    (1 - (fe.embedding <=> $1))::float8 AS score
FROM feed_embeddings fe
JOIN feeds f ON f.id = fe.feed_id
WHERE fe.user_id = $2
  AND f.user_id = $2
  AND f.deleted_at IS NULL
ORDER BY fe.embedding <=> $1
LIMIT $3
`

type RetrieveFeedPassagesParams struct {
	Embedding pgvector.Vector
	UserID    int64
	Limit     int32
}

type RetrieveFeedPassagesRow struct {
	FeedID      int32
	Title       string
	Description pgtype.Text
	Score       float64
}

func (q *Queries) RetrieveFeedPassages(ctx context.Context, arg RetrieveFeedPassagesParams) ([]RetrieveFeedPassagesRow, error) {
	rows, err := q.db.Query(ctx, retrieveFeedPassages, arg.Embedding, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetrieveFeedPassagesRow{}
	for rows.Next() {
		var i RetrieveFeedPassagesRow
		if err := rows.Scan(
			&i.FeedID,
			&i.Title,
			&i.Description,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeedEmbedding = `-- name: UpsertFeedEmbedding :exec
INSERT INTO feed_embeddings (feed_id, user_id, embedding, chunk_text, content_hash, embedded_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
ON CONFLICT (feed_id) DO UPDATE SET
    user_id      = EXCLUDED.user_id,
    embedding    = EXCLUDED.embedding,
    chunk_text   = EXCLUDED.chunk_text,
    content_hash = EXCLUDED.content_hash,
    embedded_at  = CURRENT_TIMESTAMP
`

type UpsertFeedEmbeddingParams struct {
	FeedID      int32
	UserID      int64
	Embedding   pgvector.Vector
	ChunkText   string
	ContentHash []byte
}

func (q *Queries) UpsertFeedEmbedding(ctx context.Context, arg UpsertFeedEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertFeedEmbedding,
		arg.FeedID,
		arg.UserID,
		arg.Embedding,
		arg.ChunkText,
		arg.ContentHash,
	)
	return err
}
